html-skeleton/exercises/index.html
=> html-skeleton | Max

html-links/.npmrc, html-links/index.html
=> html-links | Max

html-lists/.npmrc, html-lists/index.html
=>  html-lists | Max

html-syntax/.npmrc, html-syntax/index.html
=> completed html-syntax  | Max

html-block-and-inline/.npmrc, html-block-and-inline/index.html
=> html-block-and-inline | Max

css-box-model/.npmrc, css-box-model/index.html, css-box-model/styles.css
=> css-box-model | Max

html-forms/.npmrc, html-forms/index.html
=> html-forms | Max

javascript-primitives-and-variables/.eslintrc, javascript-primitives-and-variables/.npmrc, javascript-primitives-and-variables/index.html, javascript-primitives-and-variables/main.js
=> javascript-primitives-and-variables | Max

javascript-objects/.eslintrc, javascript-objects/.npmrc, javascript-objects/index.html, javascript-objects/main.js
=> javascript-objects | Max

javascript-functions/.eslintrc, javascript-functions/.npmrc, javascript-functions/index.html, javascript-functions/main.js
=> Javascript functions | Max

javascript-if/.eslintrc, javascript-if/.npmrc, javascript-if/index.html, javascript-if/main.js
=> javascript-if | Max

dom-querying/.eslintrc, dom-querying/.npmrc, dom-querying/index.html, dom-querying/main.js
=> dom-querying | Max

javascript-loops-practice/.eslintrc, javascript-loops-practice/.npmrc, javascript-loops-practice/add-suffix-to-all.js, javascript-loops-practice/add-suffix-to-all.test.js, javascript-loops-practice/countdown.js, javascript-loops-practice/countdown.test.js, javascript-loops-practice/filter-out-nulls.js, javascript-loops-practice/filter-out-nulls.test.js, javascript-loops-practice/filter-out-strings.js, javascript-loops-practice/filter-out-strings.test.js, javascript-loops-practice/find-index.js, javascript-loops-practice/find-index.test.js, javascript-loops-practice/get-indexes.js, javascript-loops-practice/get-indexes.test.js, javascript-loops-practice/get-student-names.js, javascript-loops-practice/get-student-names.test.js, javascript-loops-practice/includes-seven.js, javascript-loops-practice/includes-seven.test.js, javascript-loops-practice/index.html, javascript-loops-practice/odd-or-even.js, javascript-loops-practice/odd-or-even.test.js, javascript-loops-practice/sum-all.js, javascript-loops-practice/sum-all.test.js
=> Javascript loops practice | Max

javascript-custom-methods/.eslintrc, javascript-custom-methods/.npmrc, javascript-custom-methods/calculator.js, javascript-custom-methods/calculator.test.js, javascript-custom-methods/doggo.js, javascript-custom-methods/doggo.test.js, javascript-custom-methods/event-target.js, javascript-custom-methods/index.html, javascript-custom-methods/test.html
=> JavaScript custom methods | Max

javascript-constructors/.eslintrc, javascript-constructors/.npmrc, javascript-constructors/example-constructor.html, javascript-constructors/example-constructor.js, javascript-constructors/index.html, javascript-constructors/new-objects.html, javascript-constructors/new-objects.js, javascript-constructors/stopwatch.html, javascript-constructors/stopwatch.js, javascript-constructors/student.js, javascript-constructors/student.test.js, javascript-constructors/test.html
=> JavaScript constructors | Max

string-manipulation-2/.eslintrc, string-manipulation-2/.npmrc, string-manipulation-2/index.html, string-manipulation-2/src/capitalize-word.js, string-manipulation-2/src/capitalize-word.test.js, string-manipulation-2/src/capitalize-words.js, string-manipulation-2/src/capitalize-words.test.js, string-manipulation-2/src/first-chars.js, string-manipulation-2/src/first-chars.test.js, string-manipulation-2/src/last-chars.js, string-manipulation-2/src/last-chars.test.js, string-manipulation-2/src/num-vowels.js, string-manipulation-2/src/num-vowels.test.js, string-manipulation-2/src/ransom-case.js, string-manipulation-2/src/ransom-case.test.js, string-manipulation-2/src/swap-chars.js, string-manipulation-2/src/swap-chars.test.js, string-manipulation-2/src/truncate.js, string-manipulation-2/src/truncate.test.js
=> String manipulation 2 | Max

javascript-timers/.npmrc, javascript-timers/interval.html, javascript-timers/interval.js, javascript-timers/timeout.html, javascript-timers/timeout.js
=> JavaScript timers | Max

javascript-ajax/.eslintrc, javascript-ajax/.npmrc, javascript-ajax/pokemon.html, javascript-ajax/pokemon.js, javascript-ajax/users.html, javascript-ajax/users.js
=> JavaScript ajax | Max

javascript-modal/.npmrc, javascript-modal/index.html, javascript-modal/main.js, javascript-modal/styles.css
=> Javascript modal | Max

array-manipulation-2/.eslintrc, array-manipulation-2/.npmrc, array-manipulation-2/index.html, array-manipulation-2/src/ban-methods.js, array-manipulation-2/src/chunk.js, array-manipulation-2/src/chunk.test.js, array-manipulation-2/src/drop-right.js, array-manipulation-2/src/drop-right.test.js, array-manipulation-2/src/drop.js, array-manipulation-2/src/drop.test.js, array-manipulation-2/src/includes.js, array-manipulation-2/src/includes.test.js, array-manipulation-2/src/take-right.js, array-manipulation-2/src/take-right.test.js, array-manipulation-2/src/take.js, array-manipulation-2/src/take.test.js
=> Array manipulation 2 | Max

es6-const-let/.eslintrc, es6-const-let/.npmrc, es6-const-let/index.html, object-manipulation-2/.eslintrc, object-manipulation-2/.npmrc, object-manipulation-2/index.html, object-manipulation-2/src/defaults.js, object-manipulation-2/src/defaults.test.js, object-manipulation-2/src/invert.js, object-manipulation-2/src/invert.test.js, object-manipulation-2/src/omit.js, object-manipulation-2/src/omit.test.js, object-manipulation-2/src/pick.js, object-manipulation-2/src/pick.test.js
=> ES6-const-let | Max

node-process-argv/.eslintrc, node-process-argv/.npmrc, node-process-argv/all-arguments.js, node-process-argv/echo.js, node-process-argv/process.js
=> node-process-argv | Max

node-process/.npmrc
=> Node-process |  Max

node-require/.eslintrc, node-require/.npmrc, node-require/add.js, node-require/calculate.js, node-require/divide.js, node-require/multiply.js, node-require/substract.js
=> Node require | Max

node-module-system/.eslintrc, node-module-system/.npmrc, node-module-system/a-wrapped-module.js
=> Node module system | Max

node-intro/.eslintrc, node-intro/.npmrc, node-intro/hello-node.js
=> Node intro | Max

node-fs-writefile/.npmrc, node-fs-writefile/note-to-self.js, node-fs-writefile/note.txt, node-fs-writefile/write-rand.js
=> Node fs-writefile | Max

the-event-loop/.eslintrc, the-event-loop/.npmrc, the-event-loop/interval.js, the-event-loop/timeout.js
=> The event loop | Max

object-manipulation-2/.eslintrc, object-manipulation-2/.npmrc, object-manipulation-2/index.html, object-manipulation-2/src/defaults.js, object-manipulation-2/src/defaults.test.js, object-manipulation-2/src/invert.js, object-manipulation-2/src/invert.test.js, object-manipulation-2/src/omit.js, object-manipulation-2/src/omit.test.js, object-manipulation-2/src/pick.js, object-manipulation-2/src/pick.test.js
=> Object manipulation 2 | Max

node-notes-cli/.eslintrc, node-notes-cli/.npmrc, node-notes-cli/data.json, node-notes-cli/main.js
=> Node notes cli | Max

express-intro/.npmrc, express-intro/index.js, express-intro/package.json
=> Express intro | Max

express-hello-world/.npmrc, express-hello-world/index.js, express-hello-world/package.json
=> express-hello-world | Max

express-delete/.npmrc, express-delete/index.js, express-delete/package.json
=> express-delete | Max

express-get-json/.npmrc, express-get-json/index.js, express-get-json/package.json
=> Express-get-JSON | Max

express-post-json/.npmrc, express-post-json/index.js, express-post-json/package.json
=> Express-post-JSON | Max

postgres-intro/.npmrc, postgres-intro/list-of-databases.txt
=> postgresql-intro | Max

sql-aggregates/.npmrc, sql-aggregates/average-cost.sql, sql-aggregates/movie-maniacs.sql, sql-aggregates/on-the-map.sql, sql-aggregates/starring-in.sql, sql-aggregates/total-dvds.sql
=> Sql aggregates | Max

sql-join/.npmrc, sql-join/big-spenders.sql, sql-join/magic-mallrats.sql, sql-join/sassy-cast.sql, sql-join/what-and-when.sql, sql-join/where-are-they.sql
=> Sql join | Max

sql-update/.npmrc, sql-update/make-yoder.sql, sql-update/murica.sql, sql-update/sick-prank.sql
=> completed sql-update | Max

sql-select/.npmrc, sql-select/actor-forty.sql, sql-select/actor-names.sql, sql-select/all-actors.sql, sql-select/all-customers.sql, sql-select/all-films.sql, sql-select/all-genres.sql, sql-select/all-languages.sql, sql-select/cheap-to-rent.sql, sql-select/expensive-films.sql, sql-select/five-customers-emails.sql, sql-select/inactive-customers.sql, sql-select/r-rated-films.sql, sql-select/second-store-customers.sql, sql-select/ten-actor-first-names.sql, sql-select/twenty-films-of-06.sql, sql-select/two-kilmers.sql, sql-select/west-bengali-postal-codes.sql
=> Sql select | Max

sql-delete/.npmrc, sql-delete/bizzare.sql, sql-delete/diplomat.sql, sql-delete/puritanical.sql, sql-delete/sanction.sql
=> Sql delete | Max

es6-promises/.eslintrc, es6-promises/.npmrc, es6-promises/index.js, es6-promises/take-a-chance.js
=> Es6 promises | Max

array-filter/.eslintrc, array-filter/.npmrc, array-filter/index.html, array-filter/main.js, sgt-back-end/.npmrc, sgt-back-end/data.sql, sgt-back-end/index.js, sgt-back-end/package.json, sgt-back-end/schema.sql
=> Array-filter | Max

array-map/.eslintrc, array-map/.npmrc, array-map/index.html, array-map/main.js
=> Array-map | Map

array-reduce/.eslintrc, array-reduce/.npmrc, array-reduce/index.html, array-reduce/main.js
=> Array reduce | Max

es6-classes/.eslintrc, es6-classes/.npmrc, es6-classes/example-class.html, es6-classes/example-class.js, es6-classes/stopwatch.html, es6-classes/stopwatch.js, es6-classes/student.js, es6-classes/student.test.js, es6-classes/test.html
=> Es6 classes | Max

react-events-and-state/.gitignore, react-events-and-state/.npmrc, react-events-and-state/dist/index.html, react-events-and-state/package.json, react-events-and-state/src/index.jsx, react-events-and-state/webpack.config.js
=> React events and state | Max

fetch/.eslintrc, fetch/.npmrc, fetch/index.html, fetch/main.js, fetch/package.json
=> Fetch | Max

sgt-back-end/index.js
=> sgt back end | Max

api-authentication/.env.example, api-authentication/.eslintrc, api-authentication/.gitignore, api-authentication/.npmrc, api-authentication/create-token.js, api-authentication/database/data.sql, api-authentication/database/schema.sql, api-authentication/package.json, api-authentication/scripts/db-import.bash, api-authentication/server/client-error.js, api-authentication/server/error-middleware.js, api-authentication/server/index.js, api-authentication/verify-password.js, api-authorization/.env.example, api-authorization/.eslintrc, api-authorization/.gitignore, api-authorization/.npmrc, api-authorization/database/data.sql, api-authorization/database/schema.sql, api-authorization/package.json, api-authorization/scripts/db-import.bash, api-authorization/server/authorization-middleware.js, api-authorization/server/client-error.js, api-authorization/server/error-middleware.js, api-authorization/server/index.js, api-authorization/verify-token.js
=> api authorization | Max

api-authentication/.env.example, api-authentication/.eslintrc, api-authentication/.gitignore, api-authentication/.npmrc, api-authentication/create-token.js, api-authentication/database/data.sql, api-authentication/database/schema.sql, api-authentication/package.json, api-authentication/scripts/db-import.bash, api-authentication/server/client-error.js, api-authentication/server/error-middleware.js, api-authentication/server/index.js, api-authentication/verify-password.js
=> Api authentication | Max

react-context/.env.example, react-context/.gitignore, react-context/.npmrc, react-context/client/app.jsx, react-context/client/components/auth-form.jsx, react-context/client/components/navbar.jsx, react-context/client/components/page-container.jsx, react-context/client/components/redirect.jsx, react-context/client/index.jsx, react-context/client/lib/app-context.js, react-context/client/lib/decode-token.js, react-context/client/lib/parse-route.js, react-context/client/pages/auth.jsx, react-context/client/pages/home.jsx, react-context/client/pages/not-found.jsx, react-context/database/data.sql, react-context/database/schema.sql, react-context/flow.txt, react-context/nodemon.json, react-context/package.json, react-context/scripts/db-import.bash, react-context/server/client-error.js, react-context/server/error-middleware.js, react-context/server/index.js, react-context/server/public/index.html, react-context/webpack.config.js
=> React context | Max

javascript-closures/.eslintrc, javascript-closures/.npmrc, javascript-closures/index.html, javascript-closures/main.js, javascript-closures/make-adder.html, javascript-closures/make-counter.html, javascript-closures/make-sizer.html
=> JavaScript closures | Max

big-o-notation/.eslintrc, big-o-notation/.npmrc, big-o-notation/big-o.js
=> Big o notation | Max
